name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v2
    - name: 初始化
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: 还原Nuget
      run: dotnet restore
    - name: 编译
      run: dotnet build --no-restore
    - name: 测试
      run: dotnet test --no-build --verbosity normal
