name: .NET NuGet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v2
    - name: 初始化
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: 处理文本
      run: |
        sed -i "s/{version}/`cat ./Zuozishi.Common.Libs/version.txt`/" ./Zuozishi.Common.Libs/Zuozishi.Common.Libs.csproj
        sed -i "s/{GITHUB_TOKEN}/${{ secrets.GITHUB_TOKEN }}/" ./nuget.config
    - name: 还原Nuget
      run: dotnet restore
    - name: 编译
      run: dotnet build --no-restore
    - name: 测试
      run: dotnet test --no-build --verbosity normal
    - name: 打包
      run: dotnet pack --configuration Release
    - name: 发布
      run: dotnet nuget push "./Zuozishi.Common.Libs/bin/Release/Zuozishi.Common.Libs.`cat ./Zuozishi.Common.Libs/version.txt`.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"